name: build.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Exécuter une action
        uses: actions/hello-world-docker-action@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Listing files
        run: ls -al
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.27.1
      - name: Install Composer and Dependencies
        run: |
              # Télécharger et installer Composer localement
               curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=compose
               composer install
         
      - name: Run tests
        run: ./vendor/bin/phpunit      
             
